const modal=document.getElementById('modal'),title=document.getElementById('modal-title'),area=document.getElementById('game-area');
const symbols=['🍒','🔔','💎','7️⃣','⭐','🍋'];
function openGame(name){title.textContent=name;modal.classList.add('open');if(name==='Slots') slots();else if(name==='Ruleta') roulette();else if(name==='Blackjack') blackjack();else challenges()}
function closeGame(){modal.classList.remove('open')}
function slots(){area.innerHTML='<p>Créditos demo: <b id="credits">1.000</b></p><div id="reels" style="font-size:48px;letter-spacing:12px;margin:20px">❔ ❔ ❔</div><button class="cta" onclick="spin()">Girar · 25</button><p id="result"></p>'}
function spin(){let a=[0,1,2].map(()=>symbols[Math.floor(Math.random()*symbols.length)]);document.getElementById('reels').textContent=a.join('  ');let r=a[0]===a[1]&&a[1]===a[2]?'🎉 ¡Premio grande!':a[0]===a[1]||a[1]===a[2]?'✨ Premio demo':'Probá otra vez';document.getElementById('result').textContent=r}
function roulette(){area.innerHTML='<p>Elegí rojo, negro o un número.</p><div id="wheel" style="font-size:65px;margin:18px">🎡</div><button class="cta" onclick="roll()">Girar ruleta</button><p id="result"></p>'}
function roll(){let n=Math.floor(Math.random()*37),color=n===0?'verde':n%2?'rojo':'negro';document.getElementById('wheel').textContent=n;document.getElementById('result').textContent='Salió '+n+' · '+color+' (demo)'}
function blackjack(){area.innerHTML='<p>Tu objetivo: acercarte a 21 sin pasarte.</p><div id="hand" style="font-size:32px;margin:18px">🂠 🂠</div><button class="cta" onclick="deal()">Repartir cartas</button><p id="result"></p>'}
function deal(){let a=2+Math.floor(Math.random()*19),d=2+Math.floor(Math.random()*19);document.getElementById('hand').textContent='🃏 '+a+'  ·  Dealer '+d;document.getElementById('result').textContent=a>21?'Te pasaste':a===21?'¡Blackjack demo!':a>d?'Ganaste la mano demo':'Gana el dealer demo'}
function challenges(){area.innerHTML='<p>Desafío diario demo</p><div style="font-size:48px;margin:22px">🏆</div><p>Completá 3 partidas para sumar puntos.</p><button class="cta" onclick="document.getElementById(\'result\').textContent=\'¡Desafío completado! +500 puntos\'">Completar demo</button><p id="result"></p>'}
modal.addEventListener('click',e=>{if(e.target===modal)closeGame()});